(() => {
  const q=s=>document.querySelector(s), originalRender=window.render;
  let active='schedule', headerImage='';
  if(q('#syncStatus'))q('#syncStatus').style.display='none';
  document.head.insertAdjacentHTML('beforeend','<style>.chat{display:flex;gap:9px;margin:16px 0;align-items:flex-start}.chat .avatar{width:28px;height:28px;font-size:13px;margin-right:-8px;border:2px solid #fff}.chat-bubble{max-width:78%;padding:12px 14px;border-radius:4px 15px 15px;background:#eef9f8;font-size:13px;line-height:1.7}.chat-bubble small{display:block;margin-top:5px;color:#8b93a0;font-size:9px}.empty{color:#8b93a0;text-align:center;font-size:13px;padding:36px}.event-photo{cursor:zoom-in}#imageDialog{width:min(92vw,700px);background:#111;padding:12px}#imageDialog img{display:block;max-width:100%;max-height:82vh;margin:auto}.image-close{position:absolute;right:12px;top:12px;z-index:1}.hero{transition:background-image .2s}</style>');
  const tabs=q('.tabs');tabs.innerHTML='<button class="active" data-view="schedule">スケジュール</button><button data-view="messages">ひとことメッセージ</button>';
  q('#schedule').insertAdjacentHTML('afterend','<section id="messages" hidden></section>');
  document.body.insertAdjacentHTML('beforeend','<dialog id="messageDialog"><form id="messageForm"><div class="modal-header"><h2>ひとことを追加</h2><button class="close" type="button" id="closeMessage">×</button></div><label>メッセージ<textarea name="text" required rows="4"></textarea></label><fieldset><legend>投稿メンバー</legend><div class="member-picker" id="messagePicker"></div></fieldset><div class="modal-actions"><button class="ghost" type="button" id="cancelMessage">キャンセル</button><button class="save">投稿する</button></div></form></dialog><dialog id="imageDialog"><button class="close image-close" id="closeImage">×</button><img id="largeImage"></dialog>');
  const hero=q('.hero');
  const oldRender=window.render;
  window.render=function(){oldRender();headerImage=state.trip.headerImage||'';if(headerImage){hero.style.backgroundImage=`linear-gradient(#0a667888,#12769a88),url(${headerImage})`;hero.style.backgroundSize='cover';hero.style.backgroundPosition='center'}document.querySelectorAll('.event-photo').forEach(i=>i.onclick=e=>{e.stopPropagation();q('#largeImage').src=i.src;q('#imageDialog').showModal()});renderMessages();};
  q('#closeImage').onclick=()=>q('#imageDialog').close();
  tabs.onclick=e=>{if(!e.target.dataset.view)return;active=e.target.dataset.view;tabs.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===e.target));q('#schedule').hidden=active!=='schedule';q('#messages').hidden=active!=='messages';q('#fabText').textContent=active==='schedule'?'予定を追加':'ひとことを追加'};
  q('#openModal').onclick=()=>active==='schedule'?openEvent():openMessage();
  function makePicker(id,chosen=[]){q(id).innerHTML=state.members.map(m=>`<button type="button" class="member-choice ${chosen.includes(m.id)?'selected':''}" data-id="${m.id}">${avatar(m)}${m.name}</button>`).join('');q(id).querySelectorAll('button').forEach(b=>b.onclick=()=>b.classList.toggle('selected'))}
  function openMessage(){q('#messageForm').reset();makePicker('#messagePicker');q('#messageDialog').showModal()}q('#closeMessage').onclick=q('#cancelMessage').onclick=()=>q('#messageDialog').close();
  q('#messageForm').onsubmit=async e=>{e.preventDefault();let f=e.target;state.messages??=[];state.messages.push({id:Date.now(),text:f.text.value,people:[...q('#messagePicker').querySelectorAll('.selected')].map(x=>+x.dataset.id),at:new Date().toISOString()});q('#messageDialog').close();renderMessages();await save()};
  function renderMessages(){let box=q('#messages');box.innerHTML=(state.messages||[]).slice().reverse().map(m=>{let ps=m.people.map(i=>state.members.find(x=>x.id===i)).filter(Boolean);return `<article class="chat"><div>${ps.map(avatar).join('')}</div><div class="chat-bubble">${esc(m.text)}<small>${new Date(m.at).toLocaleString('ja-JP')}</small></div></article>`}).join('')||'<p class="empty">まだメッセージはありません。</p>'}
  q('#deleteMember').onclick=async()=>{if(!editMember||!confirm('このメンバーを削除しますか？'))return;let id=editMember.id;state.members=state.members.filter(m=>m.id!==id);state.events=state.events.map(e=>({...e,people:e.people.filter(x=>x!==id)}));q('#memberEditDialog').close();q('#memberDialog').close();render();await save()};
  q('#settingsForm').insertAdjacentHTML('beforeend','<label class="image-input">ヘッダー画像<input type="file" id="headerInput" accept="image/*"><span id="headerLabel">＋ 画像を選択</span></label>');
  q('#headerInput').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{state.trip.headerImage=r.result;q('#headerLabel').textContent='✓ 画像を選択しました'};r.readAsDataURL(f)};
  const oldSettings=q('#settingsForm').onsubmit;q('#settingsForm').onsubmit=async e=>{e.preventDefault();state.trip.name=e.target.tripName.value;state.trip.groupName=e.target.groupName.value;q('#settingsDialog').close();render();await save()};
  q('#openSettings').addEventListener('click',()=>{q('#headerLabel').textContent=state.trip.headerImage?'✓ 現在の画像を使用中':'＋ 画像を選択'});
})();
