(() => {
  const q=s=>document.querySelector(s), originalRender=window.render, fabLabel=()=>q('#fabText')||q('#openModal small');
  let active='schedule', headerImage='';
  if(q('#syncStatus'))q('#syncStatus').style.display='none';
  q('#openSettings').innerHTML='<img src="assets/gear-microsoft.webp" alt="設定" style="width:25px;height:25px;object-fit:contain">';
  document.head.insertAdjacentHTML('beforeend','<style>.cost-row{display:flex;align-items:center;gap:8px;margin-top:6px}.cost-row input{width:150px!important;max-width:calc(100% - 28px)!important;margin:0!important}@media(max-width:400px){.cost-row input{width:130px!important}}</style>');
  let fluentLibrary=null;import('https://cdn.jsdelivr.net/npm/fluentui-emoji-js@1.2.1/+esm').then(m=>fluentLibrary=m).catch(()=>{});const fluentUrl=e=>`https://cdn.jsdelivr.net/npm/@lobehub/fluent-emoji-3d@latest/assets/${Array.from(e).filter(x=>x!=='\ufe0f').map(x=>x.codePointAt(0).toString(16)).join('-')}.webp`;
  const repairEmoji=img=>{img.onerror=async()=>{try{if(!fluentLibrary)await new Promise(r=>setTimeout(r,400));let path=await fluentLibrary?.fromGlyph(img.alt,'3D');if(path){img.onerror=()=>img.replaceWith(document.createTextNode(img.alt));img.src='https://cdn.jsdelivr.net/gh/microsoft/fluentui-emoji@main/assets'+path}else img.replaceWith(document.createTextNode(img.alt))}catch{img.replaceWith(document.createTextNode(img.alt))}}};
  const fluentify=root=>{let w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),nodes=[];while(w.nextNode()){let n=w.currentNode,p=n.parentElement;if(p&& !['SCRIPT','STYLE','INPUT','TEXTAREA','OPTION'].includes(p.tagName)&&/[\p{Extended_Pictographic}]/u.test(n.nodeValue))nodes.push(n)}nodes.forEach(n=>{let box=document.createElement('span');box.innerHTML=n.nodeValue.replace(/\p{Extended_Pictographic}(?:\ufe0f|\u200d\p{Extended_Pictographic})*/gu,e=>`<img class="fluent-emoji" src="${fluentUrl(e)}" alt="${e}">`);box.querySelectorAll('img').forEach(repairEmoji);n.replaceWith(box)})};fluentify(document.body);new MutationObserver(m=>m.forEach(x=>x.addedNodes.forEach(n=>{if(n.nodeType===1)fluentify(n)}))).observe(document.body,{childList:true,subtree:true});
  document.head.insertAdjacentHTML('beforeend','<style>.filter-bar{display:flex;flex-wrap:wrap;gap:8px;align-items:center;margin:14px 20px 0}.filter-bar select{flex:1;padding:9px;border:1px solid #d9d6d1;border-radius:9px;background:#fff}.filter-bar button{padding:9px 11px;border:0;border-radius:9px;background:#eaf8f7;color:#0ca6aa;font:700 12px "Zen Maru Gothic"}.total-row{display:flex;gap:8px;align-items:center;width:100%;padding:8px 0}.total-row select{max-width:155px}#totalCost{flex:1;color:#0ca6aa;font:700 14px "DM Sans"}.map-link{display:inline-grid;place-items:center;width:32px;height:32px;margin:7px 0 0;border-radius:50%;background:#eaf8f7;text-decoration:none;font-size:17px}.extra-photo{margin-top:6px}.photo-slots{display:flex;gap:12px;margin-top:7px}.photo-slot{position:relative;display:grid;place-items:center;flex:1;min-width:0;aspect-ratio:1/1.2;margin:0;border:1px dashed #c9c5be;border-radius:10px;overflow:hidden;color:#0ca6aa;font-size:12px;text-align:center;cursor:pointer}.photo-slot input{position:absolute;inset:0;width:100%;height:100%;margin:0;opacity:0;cursor:pointer}.photo-slot img{width:100%;height:100%;object-fit:contain;background:#fafafa}.photo-slot span{border:0!important;padding:7px;pointer-events:none}#costField input{display:inline-block;width:calc(100% - 28px);appearance:textfield}#costField input::-webkit-outer-spin-button,#costField input::-webkit-inner-spin-button{-webkit-appearance:none;margin:0}.two-cols{grid-template-columns:minmax(0,1fr) minmax(0,1fr)!important}.two-cols label,.two-cols input{min-width:0}.two-cols input{font-size:16px}@media(max-width:390px){.photo-slots{gap:7px}.photo-slot{font-size:11px}.photo-slot span{padding:4px}.two-cols{gap:7px!important}}</style>');
  document.head.insertAdjacentHTML('beforeend','<style>.hero-top{position:relative}.hero-top #openSettings{position:absolute;top:0;right:0;z-index:3}.fluent-emoji{display:inline-block;width:1.1em;height:1.1em;margin:0;vertical-align:-.18em;object-fit:contain}.avatar>span{display:grid;place-items:center;width:100%;height:100%;line-height:0}.avatar .fluent-emoji{display:block;width:68%;height:68%;vertical-align:middle}.chat{display:flex;gap:9px;margin:16px 0;align-items:flex-start}.chat .avatar{width:28px;height:28px;font-size:13px;margin-right:-8px;border:2px solid #fff}.chat-bubble{max-width:72%;padding:12px 14px;border-radius:4px 15px 15px;background:#eef9f8;font-size:13px;line-height:1.7}.chat-bubble small{display:block;margin-top:5px;color:#8b93a0;font-size:9px}.message-delete{border:0;background:none;color:#bb817a;font-size:10px;cursor:pointer}.empty{color:#8b93a0;text-align:center;font-size:13px;padding:36px}.event-photo{cursor:zoom-in}#imageDialog{width:min(92vw,700px);background:#111;padding:12px}#imageDialog img{display:block;max-width:100%;max-height:82vh;margin:auto}.image-close{position:absolute;right:12px;top:12px;z-index:1}.hero{transition:background-image .2s}@media(max-width:760px){.two-cols{grid-template-columns:1fr!important}.two-cols input{width:100%!important}.fab{bottom:calc(env(safe-area-inset-bottom,0px) + 78px)}dialog{max-height:calc(100dvh - 120px);margin:70px auto 25px}}</style>');
  const tabs=q('.tabs');tabs.innerHTML='<button class="active" data-view="schedule">スケジュール</button><button data-view="messages">ひとことメッセージ</button>';
  q('#schedule').insertAdjacentHTML('afterend','<section id="messages" hidden></section>');
  document.body.insertAdjacentHTML('beforeend','<dialog id="messageDialog"><form id="messageForm"><div class="modal-header"><h2>ひとことを追加</h2><button class="close" type="button" id="closeMessage">×</button></div><label>メッセージ<textarea name="text" required rows="4"></textarea></label><fieldset><legend>投稿メンバー</legend><div class="member-picker" id="messagePicker"></div></fieldset><div class="modal-actions"><button class="ghost" type="button" id="cancelMessage">キャンセル</button><button class="save">投稿する</button></div></form></dialog><dialog id="imageDialog"><button class="close image-close" id="closeImage">×</button><img id="largeImage"></dialog>');
  const hero=q('.hero');
  const oldRender=window.render;
  let filterId='',totalId='';window.render=function(){let all=state.events,shown=filterId?all.filter(e=>e.people.includes(+filterId)):all,totalEvents=totalId?all.filter(e=>e.people.includes(+totalId)):[];if(filterId)state.events=shown;oldRender();state.events=all;q('#totalCost').textContent=totalId?`費用合計 ¥${totalEvents.reduce((n,e)=>n+(Number(e.cost)||0),0).toLocaleString()}`:'費用を確認するメンバーを選択';headerImage=state.trip.headerImage||'';if(headerImage){hero.style.backgroundImage=`url(${headerImage})`;hero.style.backgroundSize='cover';hero.style.backgroundPosition='center';hero.querySelectorAll('.hero-orbs').forEach(x=>x.style.display='none')}else{hero.style.backgroundImage='';hero.querySelectorAll('.hero-orbs').forEach(x=>x.style.display='')}document.querySelectorAll('.event').forEach(el=>{let e=all.find(x=>x.id===+el.dataset.id),body=el.querySelector('.event-body'),members=body.querySelector('.event-members');if(e?.place)body.querySelector('.event-place')?.remove();(e?.images||[]).slice(1).forEach(src=>body.insertAdjacentHTML('beforeend',`<img class="event-photo extra-photo" src="${src}">`));if(e?.cost)body.insertAdjacentHTML('beforeend',`<div class="event-note">¥${Number(e.cost).toLocaleString()}</div>`);if(e?.place)body.insertAdjacentHTML('beforeend',`<a class="map-link" href="${e.place}" target="_blank" rel="noopener" aria-label="地図を開く" onclick="event.stopPropagation()">🗺️</a>`);if(members)body.append(members)});document.querySelectorAll('.event-photo').forEach(i=>i.onclick=e=>{e.stopPropagation();q('#largeImage').src=i.src;q('#imageDialog').showModal()});renderMessages();};
  q('#closeImage').onclick=()=>q('#imageDialog').close();
  tabs.onclick=e=>{if(!e.target.dataset.view)return;active=e.target.dataset.view;tabs.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===e.target));q('#schedule').hidden=active!=='schedule';q('#messages').hidden=active!=='messages';q('.filter-bar').style.display=active==='schedule'?'flex':'none';fabLabel().textContent=active==='schedule'?'予定を追加':'ひとことメッセージを追加'};
  q('#openModal').onclick=()=>active==='schedule'?openEvent():openMessage();
  function makePicker(id,chosen=[]){q(id).innerHTML=state.members.map(m=>`<button type="button" class="member-choice ${chosen.includes(m.id)?'selected':''}" data-id="${m.id}">${avatar(m)}${m.name}</button>`).join('');q(id).querySelectorAll('button').forEach(b=>b.onclick=()=>b.classList.toggle('selected'))}
  let lastMessagePeople=JSON.parse(localStorage.getItem('shioriLastMessagePeople')||'[]');function openMessage(){q('#messageForm').reset();makePicker('#messagePicker',lastMessagePeople);q('#messageDialog').showModal()}q('#closeMessage').onclick=q('#cancelMessage').onclick=()=>q('#messageDialog').close();
  q('#messageForm').onsubmit=async e=>{e.preventDefault();let f=e.target,people=[...q('#messagePicker').querySelectorAll('.selected')].map(x=>+x.dataset.id);if(!people.length){alert('投稿メンバーを選択してください。');return}lastMessagePeople=people;localStorage.setItem('shioriLastMessagePeople',JSON.stringify(people));state.messages??=[];state.messages.push({id:Date.now(),text:f.text.value,people,at:new Date().toISOString()});q('#messageDialog').close();renderMessages();await save()};
  function renderMessages(){let box=q('#messages');box.innerHTML=(state.messages||[]).slice().reverse().map(m=>{let ps=m.people.map(i=>state.members.find(x=>x.id===i)).filter(Boolean);return `<article class="chat"><div>${ps.map(avatar).join('')}</div><div class="chat-bubble">${esc(m.text)}<small>${new Date(m.at).toLocaleString('ja-JP')}</small></div><button class="message-delete" data-id="${m.id}">削除</button></article>`}).join('')||'<p class="empty">まだメッセージはありません。</p>';box.querySelectorAll('.message-delete').forEach(b=>b.onclick=async()=>{if(!confirm('このメッセージを削除しますか？'))return;state.messages=state.messages.filter(m=>m.id!==+b.dataset.id);renderMessages();await save()})}
  q('#deleteMember').onclick=async()=>{if(!editMember||!confirm('このメンバーを削除しますか？'))return;let id=editMember.id;state.members=state.members.filter(m=>m.id!==id);state.events=state.events.map(e=>({...e,people:e.people.filter(x=>x!==id)}));q('#memberEditDialog').close();q('#memberDialog').close();render();await save()};
  q('#schedule').insertAdjacentHTML('beforebegin','<div class="filter-bar"><select id="filterMember"><option value="">全員の予定</option></select><button id="filterButton">絞り込み</button><div class="total-row"><strong id="totalCost">費用を確認するメンバーを選択</strong><select id="totalMember"><option value="">費用を見るメンバー</option></select></div></div>');
  q('#filterButton').onclick=()=>{filterId=q('#filterMember').value;render()};
  q('#totalMember').onchange=()=>{totalId=q('#totalMember').value;render()};
  q('#settingsForm').insertAdjacentHTML('beforeend','<label class="image-input">ヘッダー画像<input type="file" id="headerInput" accept="image/*"><span id="headerLabel">＋ 画像を選択</span></label><button class="ghost" type="button" id="removeHeader">ヘッダー画像を削除</button>');
  q('#headerInput').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{state.trip.headerImage=r.result;q('#headerLabel').textContent='✓ 画像を選択しました'};r.readAsDataURL(f)};
  q('#removeHeader').onclick=async()=>{delete state.trip.headerImage;hero.style.backgroundImage='linear-gradient(135deg,#14b4b7,#197eb1)';q('#headerInput').value='';q('#headerLabel').textContent='＋ 画像を選択';render();await save()};
  const oldSettings=q('#settingsForm').onsubmit;q('#settingsForm').onsubmit=async e=>{e.preventDefault();state.trip.name=e.target.tripName.value;state.trip.groupName=e.target.groupName.value;q('#settingsDialog').close();render();await save()};
  q('#openSettings').addEventListener('click',()=>{q('#headerLabel').textContent=state.trip.headerImage?'✓ 現在の画像を使用中':'＋ 画像を選択'});
  const place=q('#eventForm').place;place.closest('label').firstChild.textContent='Googleマップのリンク';place.type='url';place.placeholder='https://maps.google.com/...';place.closest('label').insertAdjacentHTML('afterend','<label id="costField">費用<input name="cost" type="text" inputmode="numeric" pattern="[0-9]*" placeholder="例：1500"> 円</label><div class="image-input" id="photoField">写真を添付（最大3枚）<input type="file" id="multiImages" accept="image/*" multiple><span id="multiLabel">＋ 写真を選択</span></div>');
  {let field=q('#costField'),input=field.querySelector('input'),row=document.createElement('div');row.className='cost-row';field.textContent='費用';row.append(input,document.createTextNode('円'));field.append(row)}
  let multiImages=[];q('#multiImages').onchange=e=>{let fs=[...e.target.files].slice(0,3);Promise.all(fs.map(f=>new Promise(ok=>{let r=new FileReader();r.onload=()=>ok(r.result);r.readAsDataURL(f)}))).then(x=>{multiImages=x;q('#multiLabel').textContent=`✓ ${x.length}枚を選択`})};
  q('#imageInput').closest('label').style.display='none';q('#photoField').innerHTML='写真を添付（最大3枚）<div class="photo-slots">'+[0,1,2].map(i=>`<label class="photo-slot" data-slot="${i}"><input type="file" accept="image/*"><span>＋ 画像を選択</span></label>`).join('')+'</div>';
  q('#photoField').querySelectorAll('input').forEach(input=>input.onchange=e=>{let slot=+input.closest('.photo-slot').dataset.slot,file=e.target.files[0];if(!file)return;let r=new FileReader();r.onload=()=>{multiImages[slot]=r.result;let tile=input.closest('.photo-slot');tile.innerHTML=`<input type="file" accept="image/*" style="display:none"><img src="${r.result}">`;tile.onclick=()=>{if(confirm('この写真を削除しますか？')){multiImages[slot]=null;tile.onclick=null;tile.innerHTML='<input type="file" accept="image/*"><span>＋ 画像を選択</span>';let next=tile.querySelector('input');next.onchange=input.onchange}};tile.querySelector('input').onchange=input.onchange};r.readAsDataURL(file)});
  const originalSubmit=q('#eventForm').onsubmit;q('#eventForm').onsubmit=async ev=>{ev.preventDefault();let f=ev.target,people=[...q('#memberPicker').querySelectorAll('.selected')].map(x=>+x.dataset.id);if(!people.length){alert('参加メンバーを選択してください。');return}let selectedImages=multiImages.filter(Boolean),images=selectedImages.length?selectedImages:(editEvent?.images||(imageData?[imageData]:[])),o={id:editEvent?.id||Date.now(),title:f.title.value,start:f.start.value,end:f.end.value,place:f.place.value,note:f.note.value,icon:f.icon.value,cost:f.cost.value,people,images,image:images[0]||''};state.events=editEvent?state.events.map(x=>x.id===o.id?o:x):[...state.events,o];q('#eventDialog').close();multiImages=[];render();await save()};
  const oldOpen=window.openEvent;window.openEvent=function(id){oldOpen(id);q('#eventForm').cost.value=editEvent?.cost||'';multiImages=[];q('#multiLabel').textContent='＋ 写真を選択'};
  q('#deleteEvent').onclick=async()=>{if(!editEvent||!confirm('この予定を削除してもよろしいですか？'))return;state.events=state.events.filter(e=>e.id!==editEvent.id);q('#eventDialog').close();render();await save()};
  q('#memberForm').onsubmit=async e=>{e.preventDefault();let f=e.target,m={id:editMember?.id??Date.now(),name:f.memberName.value,emoji:f.memberEmoji.value,color:f.memberColor.value};state.members=editMember?state.members.map(x=>x.id===m.id?m:x):[...state.members,m];q('#memberEditDialog').close();q('#memberDialog').close();render();await save();q('#memberButton').click()};
  const refillFilter=()=>{let fv=q('#filterMember').value,tv=q('#totalMember').value,options=state.members.map(m=>`<option value="${m.id}">${m.emoji} ${m.name}</option>`).join('');q('#filterMember').innerHTML='<option value="">全員の予定</option>'+options;q('#totalMember').innerHTML='<option value="">費用を見るメンバー</option>'+options;q('#filterMember').value=fv;q('#totalMember').value=tv};setInterval(refillFilter,1000);refillFilter();
  setInterval(()=>document.querySelectorAll('.map-link').forEach(x=>{if(!x.dataset.fixed){x.innerHTML='<img src="assets/world-map-microsoft.webp" alt="地図" style="width:23px;height:23px;object-fit:contain">';x.dataset.fixed='1'}}),300);
})();
