(() => {
  const q=s=>document.querySelector(s), originalRender=window.render, fabLabel=()=>q('#fabText')||q('#openModal small');
  let active='schedule', headerImage='';
  if(q('#syncStatus'))q('#syncStatus').style.display='none';
  document.head.insertAdjacentHTML('beforeend','<style>.filter-bar{display:flex;gap:8px;align-items:center;margin:14px 20px 0}.filter-bar select{flex:1;padding:9px;border:1px solid #d9d6d1;border-radius:9px;background:#fff}.filter-bar button{padding:9px 11px;border:0;border-radius:9px;background:#eaf8f7;color:#0ca6aa;font:700 12px "Zen Maru Gothic"}.map-link{display:inline-grid;place-items:center;width:32px;height:32px;margin:7px 0 0;border-radius:50%;background:#eaf8f7;text-decoration:none;font-size:17px}.extra-photo{margin-top:6px}.photo-slots{display:flex;gap:12px;margin-top:7px}.photo-slot{position:relative;display:grid;place-items:center;width:31%;aspect-ratio:1/1.2;margin:0;border:1px dashed #c9c5be;border-radius:10px;overflow:hidden;color:#0ca6aa;font-size:12px;text-align:center;cursor:pointer}.photo-slot input{position:absolute;inset:0;width:100%;height:100%;margin:0;opacity:0;cursor:pointer}.photo-slot img{width:100%;height:100%;object-fit:contain;background:#fafafa}.photo-slot span{padding:7px;pointer-events:none}#costField input{appearance:textfield}#costField input::-webkit-outer-spin-button,#costField input::-webkit-inner-spin-button{-webkit-appearance:none;margin:0}</style>');
  document.head.insertAdjacentHTML('beforeend','<style>.chat{display:flex;gap:9px;margin:16px 0;align-items:flex-start}.chat .avatar{width:28px;height:28px;font-size:13px;margin-right:-8px;border:2px solid #fff}.chat-bubble{max-width:72%;padding:12px 14px;border-radius:4px 15px 15px;background:#eef9f8;font-size:13px;line-height:1.7}.chat-bubble small{display:block;margin-top:5px;color:#8b93a0;font-size:9px}.message-delete{border:0;background:none;color:#bb817a;font-size:10px;cursor:pointer}.empty{color:#8b93a0;text-align:center;font-size:13px;padding:36px}.event-photo{cursor:zoom-in}#imageDialog{width:min(92vw,700px);background:#111;padding:12px}#imageDialog img{display:block;max-width:100%;max-height:82vh;margin:auto}.image-close{position:absolute;right:12px;top:12px;z-index:1}.hero{transition:background-image .2s}</style>');
  const tabs=q('.tabs');tabs.innerHTML='<button class="active" data-view="schedule">スケジュール</button><button data-view="messages">ひとことメッセージ</button>';
  q('#schedule').insertAdjacentHTML('afterend','<section id="messages" hidden></section>');
  document.body.insertAdjacentHTML('beforeend','<dialog id="messageDialog"><form id="messageForm"><div class="modal-header"><h2>ひとことを追加</h2><button class="close" type="button" id="closeMessage">×</button></div><label>メッセージ<textarea name="text" required rows="4"></textarea></label><fieldset><legend>投稿メンバー</legend><div class="member-picker" id="messagePicker"></div></fieldset><div class="modal-actions"><button class="ghost" type="button" id="cancelMessage">キャンセル</button><button class="save">投稿する</button></div></form></dialog><dialog id="imageDialog"><button class="close image-close" id="closeImage">×</button><img id="largeImage"></dialog>');
  const hero=q('.hero');
  const oldRender=window.render;
  let filterId='';window.render=function(){let all=state.events;if(filterId)state.events=all.filter(e=>e.people.includes(+filterId));oldRender();state.events=all;headerImage=state.trip.headerImage||'';if(headerImage){hero.style.backgroundImage=`url(${headerImage})`;hero.style.backgroundSize='cover';hero.style.backgroundPosition='center';hero.querySelectorAll('.hero-orbs').forEach(x=>x.style.display='none')}else{hero.style.backgroundImage='';hero.querySelectorAll('.hero-orbs').forEach(x=>x.style.display='')}document.querySelectorAll('.event-photo').forEach(i=>i.onclick=e=>{e.stopPropagation();q('#largeImage').src=i.src;q('#imageDialog').showModal()});document.querySelectorAll('.event').forEach(el=>{let e=state.events.find(x=>x.id===+el.dataset.id);if(e?.place)el.querySelector('.event-place')?.remove();if(e?.cost)el.querySelector('.event-body').insertAdjacentHTML('beforeend',`<div class="event-note">¥${Number(e.cost).toLocaleString()}</div>`);if(e?.place)el.querySelector('.event-body').insertAdjacentHTML('beforeend',`<a class="map-link" href="${e.place}" target="_blank" rel="noopener" aria-label="地図を開く" onclick="event.stopPropagation()">🗺️</a>`);(e?.images||[]).slice(1).forEach(src=>el.querySelector('.event-body').insertAdjacentHTML('beforeend',`<img class="event-photo extra-photo" src="${src}">`))});document.querySelectorAll('.event-photo').forEach(i=>i.onclick=e=>{e.stopPropagation();q('#largeImage').src=i.src;q('#imageDialog').showModal()});renderMessages();};
  q('#closeImage').onclick=()=>q('#imageDialog').close();
  tabs.onclick=e=>{if(!e.target.dataset.view)return;active=e.target.dataset.view;tabs.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===e.target));q('#schedule').hidden=active!=='schedule';q('#messages').hidden=active!=='messages';fabLabel().textContent=active==='schedule'?'予定を追加':'ひとことメッセージを追加'};
  q('#openModal').onclick=()=>active==='schedule'?openEvent():openMessage();
  function makePicker(id,chosen=[]){q(id).innerHTML=state.members.map(m=>`<button type="button" class="member-choice ${chosen.includes(m.id)?'selected':''}" data-id="${m.id}">${avatar(m)}${m.name}</button>`).join('');q(id).querySelectorAll('button').forEach(b=>b.onclick=()=>b.classList.toggle('selected'))}
  function openMessage(){q('#messageForm').reset();makePicker('#messagePicker');q('#messageDialog').showModal()}q('#closeMessage').onclick=q('#cancelMessage').onclick=()=>q('#messageDialog').close();
  q('#messageForm').onsubmit=async e=>{e.preventDefault();let f=e.target;state.messages??=[];state.messages.push({id:Date.now(),text:f.text.value,people:[...q('#messagePicker').querySelectorAll('.selected')].map(x=>+x.dataset.id),at:new Date().toISOString()});q('#messageDialog').close();renderMessages();await save()};
  function renderMessages(){let box=q('#messages');box.innerHTML=(state.messages||[]).slice().reverse().map(m=>{let ps=m.people.map(i=>state.members.find(x=>x.id===i)).filter(Boolean);return `<article class="chat"><div>${ps.map(avatar).join('')}</div><div class="chat-bubble">${esc(m.text)}<small>${new Date(m.at).toLocaleString('ja-JP')}</small></div><button class="message-delete" data-id="${m.id}">削除</button></article>`}).join('')||'<p class="empty">まだメッセージはありません。</p>';box.querySelectorAll('.message-delete').forEach(b=>b.onclick=async()=>{if(!confirm('このメッセージを削除しますか？'))return;state.messages=state.messages.filter(m=>m.id!==+b.dataset.id);renderMessages();await save()})}
  q('#deleteMember').onclick=async()=>{if(!editMember||!confirm('このメンバーを削除しますか？'))return;let id=editMember.id;state.members=state.members.filter(m=>m.id!==id);state.events=state.events.map(e=>({...e,people:e.people.filter(x=>x!==id)}));q('#memberEditDialog').close();q('#memberDialog').close();render();await save()};
  q('#schedule').insertAdjacentHTML('beforebegin','<div class="filter-bar"><select id="filterMember"><option value="">全員の予定</option></select><button id="filterButton">絞り込み</button></div>');
  q('#filterButton').onclick=()=>{filterId=q('#filterMember').value;render()};
  q('#settingsForm').insertAdjacentHTML('beforeend','<label class="image-input">ヘッダー画像<input type="file" id="headerInput" accept="image/*"><span id="headerLabel">＋ 画像を選択</span></label>');
  q('#headerInput').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{state.trip.headerImage=r.result;q('#headerLabel').textContent='✓ 画像を選択しました'};r.readAsDataURL(f)};
  const oldSettings=q('#settingsForm').onsubmit;q('#settingsForm').onsubmit=async e=>{e.preventDefault();state.trip.name=e.target.tripName.value;state.trip.groupName=e.target.groupName.value;q('#settingsDialog').close();render();await save()};
  q('#openSettings').addEventListener('click',()=>{q('#headerLabel').textContent=state.trip.headerImage?'✓ 現在の画像を使用中':'＋ 画像を選択'});
  const ownerGear=()=>{if(q('#openSettings'))q('#openSettings').style.display=owner()?'grid':'none'};setInterval(ownerGear,800);ownerGear();
  const place=q('#eventForm').place;place.closest('label').firstChild.textContent='Googleマップのリンク';place.type='url';place.placeholder='https://maps.google.com/...';place.closest('label').insertAdjacentHTML('afterend','<label id="costField">費用<input name="cost" type="text" inputmode="numeric" pattern="[0-9]*" placeholder="例：1500"> 円</label><div class="image-input" id="photoField">写真を添付（最大3枚）<input type="file" id="multiImages" accept="image/*" multiple><span id="multiLabel">＋ 写真を選択</span></div>');
  let multiImages=[];q('#multiImages').onchange=e=>{let fs=[...e.target.files].slice(0,3);Promise.all(fs.map(f=>new Promise(ok=>{let r=new FileReader();r.onload=()=>ok(r.result);r.readAsDataURL(f)}))).then(x=>{multiImages=x;q('#multiLabel').textContent=`✓ ${x.length}枚を選択`})};
  q('#imageInput').closest('label').style.display='none';q('#photoField').innerHTML='写真を添付（最大3枚）<div class="photo-slots">'+[0,1,2].map(i=>`<label class="photo-slot" data-slot="${i}"><input type="file" accept="image/*"><span>＋ 画像を選択</span></label>`).join('')+'</div>';
  q('#photoField').querySelectorAll('input').forEach(input=>input.onchange=e=>{let slot=+input.closest('.photo-slot').dataset.slot,file=e.target.files[0];if(!file)return;let r=new FileReader();r.onload=()=>{multiImages[slot]=r.result;multiImages=multiImages.filter(Boolean);let tile=input.closest('.photo-slot');tile.innerHTML=`<input type="file" accept="image/*"><img src="${r.result}">`;tile.querySelector('input').onchange=input.onchange};r.readAsDataURL(file)});
  const originalSubmit=q('#eventForm').onsubmit;q('#eventForm').onsubmit=async ev=>{ev.preventDefault();let f=ev.target,people=[...q('#memberPicker').querySelectorAll('.selected')].map(x=>+x.dataset.id),images=multiImages.length?multiImages:(editEvent?.images||(imageData?[imageData]:[])),o={id:editEvent?.id||Date.now(),title:f.title.value,start:f.start.value,end:f.end.value,place:f.place.value,note:f.note.value,icon:f.icon.value,cost:f.cost.value,people,images,image:images[0]||''};state.events=editEvent?state.events.map(x=>x.id===o.id?o:x):[...state.events,o];q('#eventDialog').close();multiImages=[];render();await save()};
  const oldOpen=window.openEvent;window.openEvent=function(id){oldOpen(id);q('#eventForm').cost.value=editEvent?.cost||'';multiImages=[];q('#multiLabel').textContent='＋ 写真を選択'};
  const refillFilter=()=>{let v=q('#filterMember').value;q('#filterMember').innerHTML='<option value="">全員の予定</option>'+state.members.map(m=>`<option value="${m.id}">${m.emoji} ${m.name}</option>`).join('');q('#filterMember').value=v};setInterval(refillFilter,1000);refillFilter();
})();
